- app/package.json
- app/src/pages/Play/YourTurnContent.tsx
- app/yarn.lock
https://trello.com/c/x4Hu71fU
Adds the Spacebar for Continue, and "S" for Skip.
Let me know if you'd like the logic in a different file / different shortcuts / different design!
> Add Keyboard Shortcuts

- app/src/components/BowlCard.tsx
- app/src/pages/CardSubmission/SubmissionCard.tsx
> detect similar words, and let user know

- app/src/components/GameRoutes.tsx
Riffing off https://github.com/avimoondra/fishbowl/pull/22 and Riffing off https://github.com/avimoondra/fishbowl/pull/25
> v2, handles error for CurrentPlayer as anonymous w/out permission change

- app/package.json
- app/src/pages/Lobby/index.tsx
- app/yarn.lock
https://trello.com/c/NwI9t8lG/6-m-l-improve-host-join-experience
I tried to avoid using an extra library, but I couldn't figure out how to get it working using the `inputRef` of the TextField, programmatically selecting that text (though I could get the input to focus), then calling `document.execCommand('copy')`.
> Add Button to copy Lobby Link

- app/src/generated/graphql.schema.json
- app/src/generated/graphql.tsx
- app/src/pages/Play/index.tsx
- app/src/pages/Play/operations.graphql
> start saving review_started_at after running out of cards or time

- app/src/pages/EndGame/index.tsx
> add play again button back to end game page

- app/src/lib/click.ts
- app/src/lib/useOnClickOutside.ts
- app/src/pages/Lobby/ControllableRoundSettings.tsx
My first time using react hooks ...... teat it apart 😉
> removes empty AddRound Form when click outside

- app/src/generated/graphql.tsx
- app/src/lib/time.ts
- app/src/pages/Play/HostControls.tsx
- app/src/pages/Play/YourTurnContent.tsx
- app/src/pages/Play/operations.graphql
> start saving turn scorings

- graphql-server/Dockerfile
Reverts avimoondra/fishbowl#48
> Revert "apply migration and metadata changes on boot"

- app/src/pages/Lobby/Inputs/index.tsx
Reverts avimoondra/fishbowl#51
> Revert "debounce real time inputs in lobby"

- app/src/pages/Lobby/Inputs/index.tsx
Reverts avimoondra/fishbowl#53
> Revert "Revert "debounce real time inputs in lobby""

- app/src/lib/score.ts
- app/src/lib/turn.ts
- app/src/pages/Play/index.tsx
https://sentry.io/organizations/fishbowl/issues/1666187786/?project=5241100&referrer=alert_email
> call start review mutation once

- app/src/pages/Lobby/WaitingRoom.tsx
https://sentry.io/organizations/fishbowl/issues/1666119209/?environment=production&project=5241100&query=is%3Aunresolved
> add copy to defer starting the game w/out all players

- app/src/App.tsx
- app/src/components/GameRoutes.tsx
- app/src/components/Layout.tsx
- app/src/contexts/Notification.ts
- app/src/pages/Home/Join.tsx
> show snackbar notifs for incorrect game code entry or url

- app/src/pages/Lobby/Inputs/AllowCardSkipsCheckbox.tsx
- app/src/pages/Lobby/Inputs/index.tsx
- app/src/pages/Play/HostControls.tsx
- app/src/pages/Play/index.tsx
- app/src/pages/Settings/index.tsx
> add ability to adjust settings mid game via Settings FAB

- app/src/generated/graphql.schema.json
- app/src/generated/graphql.tsx
- app/src/pages/Play/operations.graphql
- graphql-server/metadata/tables.yaml
in case this mutation gets run any number of times, which sometimes it does... 
https://app.logdna.com/083dfa795c/logs/view?b=1589141102262.1212745679141572611&e=1589141224574.1212746193596784647&q=ae233f9f-261f-42a5-8177-5495d67927c1%09
> delete turn scorings before inserting new ones, per turn

- .github/workflows/lint.yml
See https://github.com/avimoondra/fishbowl/pull/80#discussion_r430710647
> Fix GitHub Action .nvmrc usage

- app/src/pages/Lobby/Inputs/UsernameInput.tsx
Updates the button with more states:
> Updates the Lobby "Join" Button

- .github/workflows/build.yml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/prettier.xml
- app/src/graphql/operations.graphql
- app/src/pages/CardSubmission/AssignTeamsButton.tsx
- app/src/pages/CardSubmission/WaitingForSubmissions.tsx
Branched off https://github.com/avimoondra/fishbowl/pull/98
* Abstract `AssignTeamsButton` component
* Introduce `WaitingForSubmissionsState` enum
> Start introducing host screening state

- actions-server/src/handlers/joinGame.ts
- actions-server/src/handlers/newGame.ts
- actions-server/src/handlers/operations.graphql
- app/src/pages/Home/index.tsx
- app/src/pages/Home/operations.graphql
- app/src/pages/Lobby/index.tsx
- graphql-server/metadata/tables.yaml
Rebased version of https://github.com/avimoondra/fishbowl/pull/106, which has full context.
(I didn't know how to update that PR itself, I think I'd have to have permissions on your fork, @tannerkrewson?)
> Add 🚀🦀 rocketcrab support (pr/106)

- app/src/pages/Home/index.tsx
- app/src/pages/Home/operations.graphql
- app/src/pages/Lobby/index.tsx
follows from #112  (related to #111 #110)
> restore fe change to support rocket crab #110

- app/public/index.html
This seems to be the most common name for the game here in the UK.
> Also known as The Hat Game

- app/src/contexts/CurrentGame.ts
- app/src/graphql/operations.graphql
- app/src/lib/cards.ts
- app/src/pages/Lobby/CardSettings.tsx
- app/src/pages/Lobby/Inputs/index.tsx
- app/src/pages/Lobby/SettingsSection.tsx
- app/src/pages/Lobby/ShareSection.tsx
- app/src/pages/Lobby/WaitingRoom.tsx
- app/src/pages/Lobby/index.tsx
- app/src/pages/Lobby/operations.graphql
Depends on https://github.com/avimoondra/fishbowl/pull/120 (merged)
> enable card submission from comma separated list from host

- app/src/pages/Lobby/SettingsSection.tsx
- app/src/pages/Lobby/SettingsSummary.tsx
> provide settings summary prior to expanding

- app/src/hooks/useServerTimeOffset.ts
Fixes [APP-FQ](https://sentry.io/organizations/fishbowl/issues/2189237078/?project=5241100&query=is%3Aunresolved) (randomly hit this locally by navigating to an invalid game code route)
> Mitigate empty array mean error

- app/src/hooks/useServerTimeOffset.ts
* Fix [APP-FR](https://sentry.io/organizations/fishbowl/issues/2189238650/?project=5241100&query=is%3Aunresolved)
* Relates to https://github.com/avimoondra/fishbowl/pull/131, and I think the last of these for now
> Mitigate empty array median error

- app/src/locales/functions.ts
- app/src/locales/index.ts
Feel free to review the strings in [locize](https://www.locize.app/cat/9svqlsjm/v/latest#lng=de) or via the [PR Server](https://fishbowl-app-pr-139.onrender.com/?lng=de).
> Add German translations
